theme: jekyll-theme-minimal
title: CIT 281 - Lab 7
description: I created by own GitHub organization for the CIT minor, created my first repository, cloned my repository, created JavaScript files and initialized them as a Node.js folder, updated and committed lab file to practice with error handling, and pushed my changes to GitHub. 
